FROM node:14-alpine

ENV APP_HOME=/app
ENV API_PORT=4000
ENV WS_PORT=8000

WORKDIR $APP_HOME

COPY package.json $APP_HOME
COPY yarn.lock $APP_HOME

RUN yarn install --production

COPY --chown=node:node . .

USER node

EXPOSE $API_PORT
EXPOSE $WS_PORT

CMD ["yarn", "start:prod"]
